name: Build and Test

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Start containers
        run: docker-compose -f "docker-compose-dev.yml" up -d --build
      - name: Test container
        run: |
          curl localhost:8080/api/info/version
          echo "Heureka!!"
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose-dev.yml" down